server:
  port: 23330
spring:
  datasource:
    url: jdbc:sqlite:E:/workspace/data.db
    driverClassName: org.sqlite.JDBC
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'

cacheexpire:
  captcha: 100
  account: 36000
  order: 36000

counter:
  id: 23330
  dataCenterId: 0
  workerId: 0
  checksum: com.hyfly.milet.counter.checksum.ByteCheckSum
  bodycodec: com.hyfly.milet.counter.codec.BodyCodec
  sendip: 127.0.0.1
  sendpoit: 23301
  gatewayid: 23301