server:
  port: 23330
spring:
  datasource:
    url: jdbc:sqlite:E:/workspace/data.db
    driverClassName: org.sqlite.JDBC
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'

cacheexpire:
  captcha: 100
  account: 36000
  order: 36000

counter:
  id: 0
  dataCenterId: 0
  workerId: 0
